### ISSUE TITLE
TMS-service: Rationalise the API endpoints

### ISSUE THREAD

**Issue by Justus-at-Tazama** [tazama-lf/tms-service#128]
The current API endpoints for the respective ISO20022 messages are:

`pain.001` - execute
`pain.013` - quoteReply
`pacs.008` - transfer
`pacs.002` - transfer-response

Note:  Discussion required before starting 

Acceptance criteria:
1. Create v1 of the TMS API
2. Rationalise the names to be less Mojaloop and more ISO20022
3. Standardise the names to have some sort of consistent pattern (i.e. use the anticipated `TxTp` value as the name of the endpoint)
4. Remove the validation of the `TxTp` object from the API endpoint
5. Add the `TxTp` object (key and value) to the incoming message based on the end-point where the message is received.
6. Update documentation
7. Update swagger doc
8. Decommission previous end points

**Comment by Sandy-at-Tazama** [comment]
Please rename as follows


![Image](https://github.com/frmscoe/tms-service/assets/142333955/beefd296-496b-4ce6-9455-f9dea305e7ae)
