### ISSUE TITLE
Fix the Othr data structure in the ISO20022 message implementation

### ISSUE THREAD

**Issue by Justus-at-Tazama** [tazama-lf/tms-service#177]
### Description of issue
The ISO20022 messages that are ingested at the TMS API have entity identifier information presented as a single object, but the information should be arranged in an array (even if there is only a single value).

The ISO20022 object `FIToFICstmrCdtTrf` in the pacs.008 is incorrectly labelled as `FIToFICstmrCdt`.

The following repositories and files are affected:

https://github.com/search?q=org%3Afrmscoe%20FIToFICstmrCdt&type=code

### Expected behaviour
Every ISO20022 message contains a data object for entity identification. The object should be an array, not a single object, e.g.:

```json
    "Dbtr": {
        "Nm": "April Blake Grant",
        "Id": {
            "PrvtId": {
                "DtAndPlcOfBirth": {
                    "BirthDt": "1968-02-01",
                    "CityOfBirth": "Unknown",
                    "CtryOfBirth": "ZZ"
                },
                "Othr": [ -- array here
                    {
                        "Id": "+27730975224",
                        "SchmeNm": {
                            "Prtry": "MSISDN"
                        }
                    }
                ]
            },
            "CtctDtls": {
                "MobNb": "+27-730975224"
            }
        }
    }
```

### Actual behaviour
The `Othr` object is a single object instead of an array, e.g.:

```json
    "Dbtr": {
        "Nm": "April Blake Grant",
        "Id": {
            "PrvtId": {
                "DtAndPlcOfBirth": {
                    "BirthDt": "1968-02-01",
                    "CityOfBirth": "Unknown",
                    "CtryOfBirth": "ZZ"
                },
                "Othr": { -- no array here
                    "Id": "+27730975224",
                    "SchmeNm": {
                        "Prtry": "MSISDN"
                    }
                }
            },
            "CtctDtls": {
                "MobNb": "+27-730975224"
            }
        }
    }
```

### Recreation Steps
Not applicable

### Proposed solution
Allow the TMS API to ingest ISO20022 messages where the `Othr` object is an array.
Messages and objects affected:
 - pain.001.001.11
    - `CstmrCdtTrfInitn.GrpHdr.InitgPty.Id.PrvtId.Othr`
    - `CstmrCdtTrfInitn.PmtInf.Dbtr.Id.PrvtId.Othr.Id`
    - `CstmrCdtTrfInitn.PmtInf.DbtrAcct.Id.Othr.Id`
    - `CstmrCdtTrfInitn.PmtInf.CdtTrfTxInf.Cdtr.Id.PrvtId.Othr.Id`
    - `CstmrCdtTrfInitn.PmtInf.CdtTrfTxInf.CdtrAcct.Id.Othr.Id`
 - pain.013.001.09
    - `CdtrPmtActvtnReq.GrpHdr.InitgPty.Id.PrvtId.Othr.Id`
    - `CdtrPmtActvtnReq.PmtInf.Dbtr.Id.PrvtId.Othr.Id`
    - `CdtrPmtActvtnReq.PmtInf.DbtrAcct.Id.Othr.Id`
    - `CdtrPmtActvtnReq.PmtInf.CdtTrfTxInf.Cdtr.Id.PrvtId.Othr.Id`
    - `CdtrPmtActvtnReq.PmtInf.CdtTrfTxInf.CdtrAcct.Id.Othr.Id`
 - pacs.008.001.10
    - `FIToFICstmrCdtTrf.CdtTrfTxInf.InitgPty.Id.PrvtId.Othr.Id`
    - `FIToFICstmrCdtTrf.CdtTrfTxInf.Dbtr.Id.PrvtId.Othr.Id`
    - `FIToFICstmrCdtTrf.CdtTrfTxInf.DbtrAcct.Id.Othr.Id`
    - `FIToFICstmrCdtTrf.CdtTrfTxInf.Cdtr.Id.PrvtId.Othr.Id`
    - `FIToFICstmrCdtTrf.CdtTrfTxInf.CdtrAcct.Id.Othr.Id`
 - pacs.002.001.12
    - none

### Impact
1. **TMS API**: the current validation of the incoming record will need to be updated to handle an array
2. **Mojaloop PPA**: the PPA converts the Mojaloop messages to an Actio ISO message without the array and must be updated to output the array instead
3. **BankservAfrica / BCEAO PPA**: the PPA converts the incoming data to an Actio ISO message without the array and must be updated to output the array instead
4. **Data preparation service**: The data preparation service turns the `Othr` object into an array during pseudonymisation. This routine will no longer need to convert the object to an array, but will need to be updated to merely insert the pseudonym into the array as an element.
5. **Beyond**: No change required. Data preparation has already converted the object to an array.

**update to original impact assessment**
number 4. Changes: data preparation service does not turn the othr object into an array which means point 5 is not true
6. Some rules have queries that the use pacs.008 and need to be updated (naming convention change)
7. Database creation needs to be updated (Full stack docker and postman impacts)
8. Postman tests need to be updated

### Testing guidelines
1. Regression testing

## Acceptance Criteria
1. Expand the `Othr` object in the above messages and objects
2. Update coe-lib 
3. Update TMS-API swagger
4. Update to data prep to create the entity in the database
8. Version bump TMS & data prep
9. Regression testing
10. Allow the correct specification of the pacs.008 message in the TMS API 
11. Update ISO20022 object `FIToFICstmrCdt` in pacs.008 to `FIToFICstmrCdtTrf`
12. Update the rules using `FIToFICstmrCdt` to `FIToFICstmrCdtTrf`
13. Update full-stack-docker database creation
14. Update queries in coe-lib

> **Note**
With the expansion of the `Othr` object into an array, it is conceivable that a client system can send in multiple different values to use as an identifier for the entity or their accounts. At the moment, Tazama does not have a mechanism to unpack this array into the data model. For the purposes of this change, we will assume that the client system will only send in a single element in this array, and that element will be accessible as `Othr[0]` in data preparation and any other Tazama processor that interacts with this object.

FYI - Merged https://github.com/frmscoe/tms-service/issues/150 into this ticket

**Comment by Justus-at-Tazama** [comment]
Resolve the following: The Data Preparation service creates an Entity with the identity information in the `Othr` structure - determine which and how to use multiple identification elements in the `Othr` array.

**Comment by Justus-at-Tazama** [comment]
Add https://github.com/frmscoe/tms-service/issues/150 to the scope of this ticket so that the pacs.008 object definition bug can be fixed at the same time

**Comment by Sandy-at-Tazama** [comment]
Add account
Define a process to resolve multiple entries in the array

**Comment by Lenbkr** [comment]
Parking to prioritize the ESLint incompatibilities between repositories

**Comment by JeanPierreNell** [comment]
In relation to point 4 and 5 of the impact assessment, 

The Dataprep service was rolled into TMS , and no longer saves Othr as an array, if it did in the past. Queries in the FRM-COE-LIB also requires updating, and effected rules will require version bumps and testing.

**Comment by JeanPierreNell** [comment]
In relation to point 8 of the impact assessment, 

Some rules are using queries NOT found in the library, which require changes made as well.
