### ISSUE TITLE
Token Validation at TMS API

### ISSUE THREAD

**Issue by johanfol** [tazama-lf/tms-service#184]
As the TMS API, I want to validate the expiration and signature of Tazama format tokens so that only valid tokens are accepted.

Acceptance Criteria:

- [x] The system must require a bearer token in the Authorization header.
- [x] The Authentication Library must validate the token's expiration date.
- [x] The Authentication Library must validate the token's signature using public keys.
- [x] The Authentication Library must reject invalid or expired tokens.
- [x] The Authentication Library must log any validation errors.
- [x] The TMS API must integrate with Authentication Library to Validate the external token.
- [x] The TMS API must return a 401: Unauthorized exception for any token validation failures.
- [x] The TMS API must have a configurable `AUTHENTICATED` variable, which if switched to `false`, not require an Auth header, and skip all validations and authorization.

**Comment by Justus-at-Tazama** [comment]
@johanfol - Can we please add a separate and authentication-specific environment variable to turn the authentication service on and off? If we are piggy-backing off the existing `NodeENV` variable, we won't be able to test this effectively in pre-production environments. The combination of the two concepts into a single variable also defeats our "separation of concerns" design principle.
